--- #YAML:1.0
name: Number-Compare-Date
version: 0.02
license: perl
distribution_type: module
requires:
  Date::Parse: 2.27
  Number::Compare: 0.01
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Number::Compare::Date:
    file: lib/Number/Compare/Date.pm
    version: 0.02
generated_by: Module::Build version 0.18_02
